# Site settings
title: The Web and Biology | Schmidtyworks
email: mschmidty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on land management as a wildlife biologist for the Bereau of Land Management. 
baseurl: "/"  # the subpath of your site, e.g. /blog/
url:   # the base hostname & protocol for your site
# Build settings
markdown: kramdown
encoding: utf-8
exclude: [
	.git,
	.gitignore,
	.DS_store,
	CNAME,
	svg,
	src,
	scss,
	.sass-cache,
	package.json,
	gulpfile.js,
	node_modules,
	readme.md,
	main.css
]

